# Generated by Django 2.0 on 2020-01-16 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Cliente'), (1, 'Comum'), (2, 'Admin')], default=1, verbose_name='Tipo')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo')),
                ('birdayth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
