# Generated by Django 2.0 on 2020-01-16 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Mailbag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=200)),
                ('entrega', models.CharField(choices=[(1, 'manhã 08:00'), (2, 'tarde 11:00'), (3, 'manhã 14:00'), (4, 'manhã 16:00')], default=1, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Malote',
                'verbose_name_plural': 'Malotes',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('po', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'uso dos alunos'), (2, 'uso dos professores'), (3, 'carta')])),
                ('seg_choices', models.IntegerField(blank=True, choices=[(1, 'DIGITAR'), (2, 'ESCANEAR')], null=True)),
                ('date_period', models.DateField()),
                ('date_to_finish', models.DateField()),
                ('subject', models.TextField(blank=True, null=True)),
                ('revision', models.IntegerField(choices=[(0, 'sem revisão'), (1, 'antes de ser cherocado'), (2, 'visto da revisão')], default=0)),
                ('comment_seg', models.TextField(blank=True, null=True)),
                ('xerox_choices', models.CharField(blank=True, max_length=20, null=True)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('copy_original', models.IntegerField(blank=True, null=True)),
                ('quant_grampos', models.IntegerField(blank=True, default=0, null=True)),
                ('pre_impress_comment', models.TextField(blank=True, null=True)),
                ('copy_choices', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('diciplina', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Disciplina')),
                ('local', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Local')),
                ('mailbag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbags', to='core.Mailbag')),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='po',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Request'),
        ),
        migrations.AddField(
            model_name='po',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
