# Generated by Django 2.0 on 2020-01-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200117_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='OBS PARA COPIADORA'),
        ),
        migrations.AlterField(
            model_name='po',
            name='comment_seg',
            field=models.TextField(blank=True, null=True, verbose_name='OBS PARA  SEG'),
        ),
        migrations.AlterField(
            model_name='po',
            name='copy_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='NUM DE COPIAS'),
        ),
        migrations.AlterField(
            model_name='po',
            name='diciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Disciplina'),
        ),
        migrations.AlterField(
            model_name='po',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Local'),
        ),
        migrations.AlterField(
            model_name='po',
            name='po',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero PO'),
        ),
        migrations.AlterField(
            model_name='po',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Request'),
        ),
        migrations.AlterField(
            model_name='po',
            name='revision',
            field=models.IntegerField(choices=[(0, 'sem revisão'), (1, 'antes de ser cherocado'), (2, 'visto da revisão')], default=0, verbose_name='REVISÃO'),
        ),
        migrations.AlterField(
            model_name='po',
            name='seg_choices',
            field=models.IntegerField(blank=True, choices=[(1, 'DIGITAR'), (2, 'ESCANEAR')], null=True, verbose_name='INFO PARA O SEG'),
        ),
        migrations.AlterField(
            model_name='po',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='ASSUNTO'),
        ),
        migrations.AlterField(
            model_name='po',
            name='type',
            field=models.IntegerField(choices=[(1, 'uso dos alunos'), (2, 'uso dos professores'), (3, 'carta')], verbose_name='TIPO DO MATERIAL USADO'),
        ),
        migrations.AlterField(
            model_name='po',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='po',
            name='xerox_choices',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NUM COPIAS ORIGINAIS'),
        ),
    ]
