# Generated by Django 2.0 on 2020-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_po_servico_qdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='grade',
            field=models.CharField(max_length=10, verbose_name='Grade escolar'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Requisitante'),
        ),
    ]
